### ISSUE TITLE
case sensitive for iOs

### ISSUE THREAD

**Issue by proiettile** [mad-max/skin.moddedconfluence#11]
Check links to media to verify the file names match with the code (for example Header.png in Home and Mp3.png in Music Visualization).

**Comment by proiettile** [comment]
In Home.xml all Header.png link must be corrected in header.png
In Media/Flagging/Audio the file mp3.png must be renamed in MP3.png (I don't know if there are other misnamed files).

**Comment by mad-max** [comment]
thanks for the hint

**Comment by mad-max** [comment]
forgot to close...closed by PR from proiettile...thanks

**Comment by proiettile** [comment]
In 1.0.8 the file in flagging/audio is still mp3.png and not MP3.png, so it still doesn't show in music visualization.

Also I can not visualize the rating stars in ATV2. It show the rating0 correctly, but when  i try to add stars to the rating they don't show, maybe due to the same case sensitive issue.

**Comment by mad-max** [comment]
Ah, your PR was only for header.png? thought it was mp3, too...
Repoened...

**Comment by proiettile** [comment]
I would, but it seems that I can't rename files in structure here. Should I delete mp3.png and upload MP3.png?

**Comment by mad-max** [comment]
You should be able to change the filename on your side, push it to your repo and make PR...
I can handle this just editing here, but I would be interested if you are able to change binaries or not...
Can you make an PR?

**Comment by proiettile** [comment]
I've tried (went to my fork / skin.moddedconfluence / media / flagging / audio), but I can't change the filename, I have no tools to do that.
